frase = ('Curso em Vídeo Python    ')
print(len(frase))
print(frase.find('deo'))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.capitalize())
print(frase.lower())
print(frase.title())
print(frase.replace('Curso em Vídeo Python', 'Aprenda Python'))
print(frase.split())
print('--'.join(frase))
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15])
print(frase[1:15:2])
print(frase[::2])
print(frase[1::2])
print("""iueuhuhue uehuh asoiajso iuahsiuh iuh asiauhsi uahs a
uahsuahsuahush sahs auhs auhuahuah sauh deuh ahspejid iouehi euhd eudheie deudh uhee
uhduehd euhdeuhuedh euhdeu deuhde uheuheuhd euhde udheuh a~dhaçoeuh çahça iuh""")
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('V'))
print(len(frase))
print(len(frase.strip()))
frase.replace('Python', 'Android')
print(frase)
frase = frase.replace('Python', 'Android')
print(frase)
print(frase.find('Curso'))
print(frase.find('Vídeo'))
print(frase.find('video'))
print(frase.lower().find('vídeo'))
dividido = frase.split()
print(dividido)
print(dividido[0])
print(dividido[2][3])
